name: 新しい機能の実装
description: 新しい機能の実装に関するチケット
body:
  - type: input
    id: background
    attributes:
      label: このタスクが必要な背景
      description: この機能が必要な理由を説明してください
      placeholder: "例: ユーザーがログインできるようにするため"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: このタスクの内容
      description: この機能が何をするのか、どのように実装されるのかを説明してください
      placeholder: |
        例:
        - 認証ライブラリを導入する
        - ログインフォームを作成する
        - ログインボタンを押したときにログイン処理を実行する
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: このタスクが Done になる条件
      description: この機能が実装されたときにどのような結果が得られるかを説明してください
      placeholder: |
        例:
        - [ ] ユーザー名とパスワードをフォームに入力し、ログインボタンをクリックすると、ユーザーがログインできる
        - [ ] ユーザー名とパスワードが間違っている場合、エラーメッセージが表示される
      value: "- [ ] "
  - type: textarea
    id: design-doc
    attributes:
      label: 設計書・関連資料
      description: この機能の設計書や関連資料があればリンクを貼ってください
      placeholder: "例: https://example.com/design"
